"""
Migration: Archive legacy signals (Phase 1 — V3.1 Enterprise Cleanup).

Identifies and moves signals generated by the old engine into archive_signals:
  - timeframe = '5m'  (pre-MTF scanner)
  - strategy  != 'MTF_SMC_STRICT'  (any other old strategy string)

Production signals table is left with only V3 MTF signals afterward.
Records are NOT deleted from the database — they are moved to archive_signals.

Usage:
    python -m app.database.migrations.archive_legacy
    # or inside docker:
    docker compose exec bot python -m app.database.migrations.archive_legacy
"""
from __future__ import annotations

import asyncio
import sys
from datetime import datetime, timezone

from sqlalchemy import select

from app.database.models import ArchivedSignal, Signal
from app.database.session import SessionLocal, engine
from app.database.models import Base


LEGACY_TF = "5m"
NEW_STRATEGY = "MTF_SMC_STRICT"


async def run_migration() -> None:
    # Ensure archive table exists
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with SessionLocal() as session:
        # Identify legacy signals
        result = await session.execute(
            select(Signal).where(
                (Signal.timeframe == LEGACY_TF) |
                (Signal.strategy != NEW_STRATEGY)
            ).order_by(Signal.id)
        )
        legacy: list[Signal] = list(result.scalars().all())

    if not legacy:
        print("✅ No legacy signals found — archive is already clean.")
        return

    tf_5m = [s for s in legacy if s.timeframe == LEGACY_TF]
    old_engine = [s for s in legacy if s.strategy != NEW_STRATEGY and s.timeframe != LEGACY_TF]

    print(f"Found {len(legacy)} legacy signals to archive:")
    print(f"  5m timeframe:    {len(tf_5m)}")
    print(f"  Old engine:      {len(old_engine)}")
    print()

    archived_ids: list[int] = []

    async with SessionLocal() as session:
        for sig in legacy:
            if sig.timeframe == LEGACY_TF:
                reason = "legacy_5m"
            else:
                reason = f"legacy_engine:{sig.strategy}"

            arch = ArchivedSignal(
                original_id=sig.id,
                archive_reason=reason,
                archived_at=datetime.now(timezone.utc),
                symbol=sig.symbol,
                side=sig.side,
                timeframe=sig.timeframe,
                confidence=sig.confidence,
                risk_level=sig.risk_level,
                strategy=sig.strategy,
                reasons=sig.reasons or "",
                entry_low=sig.entry_low,
                entry_high=sig.entry_high,
                tp1=sig.tp1,
                tp2=sig.tp2,
                tp3=sig.tp3,
                stop_loss=sig.stop_loss,
                risk_reward=sig.risk_reward,
                status=sig.status,
                pnl_pct=sig.pnl_pct or 0.0,
                created_at=sig.created_at,
                closed_at=sig.closed_at,
            )
            session.add(arch)
            archived_ids.append(sig.id)

        await session.commit()

    print(f"✅ Archived {len(archived_ids)} signals → archive_signals table")

    # Remove from production signals
    async with SessionLocal() as session:
        for sig_id in archived_ids:
            sig = await session.get(Signal, sig_id)
            if sig is not None:
                await session.delete(sig)
        await session.commit()

    print(f"✅ Removed {len(archived_ids)} legacy signals from production signals table")
    print()
    print("Summary:")
    print(f"  Archived: {len(archived_ids)}")
    print(f"  Remaining in production: see signals table")
    print()
    print("Dashboard will now only show 15m/1h/4h/1d signals from MTF_SMC_STRICT engine.")


if __name__ == "__main__":
    asyncio.run(run_migration())
